### ISSUE TITLE
Talk by Kririll Mueller about DBI?

### ISSUE THREAD

**Issue by petermeissner** [rusershamburg/meetup-repo#12]
Hey,

I just had a chat with Kirill Mueller and he was asking if he could talk about DBI at the next Meetup (Is there a date already scheduled?)

Discuss!

:-)

**Comment by Tazinho** [comment]
Hey Peter, this sounds super nice. Initially we set up a plan for the year, where our autumn meetup would appear at september 20th (thursday). So in best case it would be somewhere around that, but if another date suits better for Kirill, we are mostly flexible.

So feel free to propose a date and after this is fix, we can look for a location and (maybe) one or two more speakers.

**Comment by petermeissner** [comment]
pushed conversation to twitter direct message so you can interact with Kirill in person.

**Comment by henningsway** [comment]
this would be absolutely awesome!

**Comment by Tazinho** [comment]
Closed for this year, but hopefully not forever ;) @krlmlr
