### ISSUE TITLE
background graphic for twitter account

### ISSUE THREAD

**Issue by Tazinho** [rusershamburg/meetup-repo#9]
good ideas or new creations anyone?

**Comment by petermeissner** [comment]
The skyline from the logo?

![](https://pbs.twimg.com/profile_images/834717177328570370/qQWFXFfU_400x400.jpg)

**Comment by petermeissner** [comment]
![image](https://user-images.githubusercontent.com/939139/37259094-6ae4b5fa-2582-11e8-808c-018a7b18f0c3.png)

**Comment by petermeissner** [comment]
![image](https://user-images.githubusercontent.com/939139/37259114-af453d82-2582-11e8-9120-539eec72b9fb.png)

**Comment by petermeissner** [comment]
![image](https://user-images.githubusercontent.com/939139/37259150-16b24c08-2583-11e8-8119-3217b2b92927.png)

**Comment by Tazinho** [comment]
Cool, ich habe mal nr 3 reingesetzt. 1 ist langweilig ;-) 2 passt nicht von der Skalierung und 4. mein erster Favorit, wirkt leider doch unfreundlich von der Farbwahl. 3 finde ich toll, aber vlt. bin ich auch zu unkritisch :D

**Comment by Tazinho** [comment]
@petermeissner do you have image 3 or another cool graphic in another resolution?
I would like to use it also for our youtube channel.
However, that would require a minimum resolution of 2048 * 1152 pixels.

**Comment by petermeissner** [comment]
https://api.mapbox.com/styles/v1/petermeissner/cjeoqbnatdjng2rpuhivuylzq.html?fresh=true&title=true&access_token=pk.eyJ1IjoicGV0ZXJtZWlzc25lciIsImEiOiJjaWg2M2FvcmQwMDBsdnFseXVxbGNqMjQxIn0.sjwDM72Mu8FVseRUPWUVlQ#10.83/53.5173/9.9272

That's the URL to the map. Unfortunately I do not have a monitor that is high resolution enough to make a screenshot that will suffice those dimensions you need for Youtube - but maybe someone else has one?

**Comment by Tazinho** [comment]
Thanks Peter! Unfortunately I have the same issue with my monitor. @henningsway can you help out?
